import React, { useState } from 'react';
import './App.css';
import { InstantSearch, SearchBox, Hits } from 'react-instantsearch-dom';
import algoliasearch from 'algoliasearch';
import Eyeball from 'react-eyeball';

// Create a search client
const searchClient = algoliasearch('3AUHR4IE0C', 'b152fa9673ced6bc795ad370b729bfd2');

// Import Algolia components
function App() {
  const [searchQuery, setSearchQuery] = useState('');

  const handleSearch = async () => {
    // Perform Algolia search here using searchQuery
    // Store the search results in searchResults state
  };

  return (
    <div className="App">
      <header className="App-header">
      
        <span> An open source book. Content generated by GPT4-image-preview.</span>
        
        <Eyeball />
        <h1>
          Crepuscular Rays
        </h1>
      
      
        <div>
        
          {/* Wrap the search components with InstantSearch */}
          <InstantSearch
            searchClient={searchClient} // Provide the searchClient option
            indexName="Crepuscular_Rays"
          >
            {/* Add the SearchBox component */}
            <SearchBox
              className="search-box"
              translations={{
                placeholder: 'crepuscular rays',
              }}
            />
            <img height="24px" src="crepuscular_rays/images/Algolia-logo-white.png" alt="Algolia logo" />
            {/* Add the Hits component to display search results */}
            <Hits 
            className="hitslist"
            hitComponent={SearchResult} />
          </InstantSearch>
        </div>
        </header>
    </div>
  );
}

// Define a component to render each search result
const SearchResult = ({ hit }) => (
  <div key={hit.id} className="grid-item">
    <a href={hit.url}>
      <img src={hit.image} height="100" alt="journal page" />
    </a>
    <a href={hit.url}>{hit.title}</a>
  </div>
);

export default App;
